"""
AI Call Analysis & Threat Assessment PDF Report Generation Service
"""
import asyncio
from io import BytesIO
from typing import Any
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas


def _generate_pdf_sync(payload: dict[str, Any]) -> bytes:
    buf = BytesIO()
    pdf = canvas.Canvas(buf, pagesize=A4)
    _, height = A4

    call_id = str(payload.get("call_id", "UNKNOWN"))
    call_number = str(payload.get("call_number", "Unknown"))
    started_at = str(payload.get("started_at", "N/A"))
    risk_score = float(payload.get("risk_score", 0.0))
    risk_level = str(payload.get("risk_level", "SAFE")).upper()
    transcription = str(payload.get("transcription", "")).strip() or "No speech recorded."
    keywords: list[str] = payload.get("detected_keywords", [])

    # Header Banner
    if risk_level == "DANGER":
        pdf.setFillColorRGB(0.78, 0.12, 0.12)
    elif risk_level == "WARNING":
        pdf.setFillColorRGB(0.85, 0.55, 0.10)
    else:
        pdf.setFillColorRGB(0.12, 0.55, 0.25)

    pdf.rect(0, height - 70, 595.27, 70, fill=1, stroke=0)

    # Title
    pdf.setFillColorRGB(1, 1, 1)
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(36, height - 38, "A.E.G.I.S Call Threat Intelligence Report")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(36, height - 54, "Total Communication Security & Deepfake Voice Defense")

    # Content Coordinates
    y = height - 100

    def draw_label_value(label: str, value: str) -> None:
        nonlocal y
        pdf.setFont("Helvetica-Bold", 10)
        pdf.setFillColorRGB(0.2, 0.2, 0.2)
        pdf.drawString(36, y, f"{label}:")
        pdf.setFont("Helvetica", 10)
        pdf.setFillColorRGB(0.1, 0.1, 0.1)
        pdf.drawString(160, y, value)
        y -= 18

    # Metadata
    draw_label_value("Call Reference", call_id)
    draw_label_value("Caller Contact", call_number)
    draw_label_value("Session Timestamp", started_at)
    draw_label_value("Overall Risk Score", f"{risk_score * 100:.1f}% ({risk_level})")
    draw_label_value("Threat Keywords", ", ".join(keywords) if keywords else "None detected")

    y -= 10
    pdf.setStrokeColorRGB(0.8, 0.8, 0.8)
    pdf.setLineWidth(1)
    pdf.line(36, y, 559, y)
    y -= 24

    # Threat Analysis Section
    pdf.setFont("Helvetica-Bold", 12)
    pdf.setFillColorRGB(0.15, 0.15, 0.15)
    pdf.drawString(36, y, "Threat Assessment Summary")
    y -= 18

    pdf.setFont("Helvetica", 10)
    if risk_level == "DANGER":
        advice = (
            "CRITICAL THREAT: High probability of AI voice impersonation or coercive social engineering. "
            "Do not share OTPs, PINs, bank details, or transfer funds. Block this contact immediately."
        )
    elif risk_level == "WARNING":
        advice = (
            "SUSPICIOUS ACTIVITY: Potential scam patterns or acoustic anomalies detected. "
            "Exercise extreme caution and independently verify the caller through official channels."
        )
    else:
        advice = "SAFE: No malicious deception or synthetic voice spoofing was flagged during this session."

    for line in simpleSplit(advice, "Helvetica", 10, 523):
        pdf.drawString(36, y, line)
        y -= 15

    y -= 15
    pdf.setFont("Helvetica-Bold", 12)
    pdf.setFillColorRGB(0.15, 0.15, 0.15)
    pdf.drawString(36, y, "Call Transcription")
    y -= 18

    pdf.setFont("Helvetica", 9)
    pdf.setFillColorRGB(0.25, 0.25, 0.25)
    lines = simpleSplit(transcription, "Helvetica", 9, 523)
    for line in lines:
        if y < 60:
            pdf.showPage()
            y = height - 50
            pdf.setFont("Helvetica", 9)
            pdf.setFillColorRGB(0.25, 0.25, 0.25)
        pdf.drawString(36, y, line)
        y -= 14

    # Footer
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.setFillColorRGB(0.5, 0.5, 0.5)
    pdf.drawString(36, 30, "Generated by A.E.G.I.S NLP Realtime Threat Intelligence Platform.")

    pdf.save()
    buf.seek(0)
    return buf.read()


async def generate_call_report_pdf(payload: dict[str, Any]) -> bytes:
    """Async wrapper to offload CPU-bound PDF generation to a worker thread."""
    return await asyncio.to_thread(_generate_pdf_sync, payload)
